name: build
on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

# make sure that GITHUB_TOKEN has permissions
permissions:
  contents: write

jobs:
  build-slides:
    uses: ./.github/workflows/template_build.yaml
    with:
      tex-workdir: slides
      tex-file: main
      output-name: 24_emb_presentation

  build-article:
    uses: ./.github/workflows/template_build.yaml
    with:
      tex-workdir: article
      tex-file: main
      output-name: 24_emb_article
