name: release
on:
  push:
    tags:
      - 'v*'

env:
  # without extension
  # see env.OUTPUT_NAME in `build.yaml`
  ARTIFACT_NAME_ARTICLE: 24_emb_article
  ARTIFACT_NAME_PRESENTATION: 24-emb-presentation

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  release:
      runs-on: ubuntu-latest
      needs: build
      # make sure that GITHUB_TOKEN has permissions
      permissions:
        contents: write
      steps:
        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: ${{ env.ARTIFACT_NAME }}
          
        - name: Create release
          uses: ncipollo/release-action@v1.14.0
          with:
            artifacts: ${{ env.ARTIFACT_NAME_ARTICLE }}/*, ${{ env.ARTIFACT_NAME_PRESENTATION }}/*
            body: "Release of version ${{ github.ref_name }}"
            allowUpdates: true
